name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x] # Node version

    steps:
      # Step 1: Repo checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build project (if package.json has "build" script)
      - name: Build project
        run: npm run build --if-present

      # Step 5: Skip tests (no Jest)
      - name: Skip tests
        run: echo "No tests to run. Skipping..."

      # Step 6: Deploy step (optional)
      # Yaha apna deploy command add karein (Heroku, Render, Docker, etc.)
      # - name: Deploy to server
      #   run: npm run deploy
