name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted   # 👈 self-hosted likhna hai agar apne EC2 runner use karna hai

    strategy:
      matrix:
        node-version: [22.x] # Node version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Skip tests
        run: echo "No tests to run. Skipping..."

      # Deployment step example
      # - name: Deploy to server
      #   run: |
      #     ssh user@server "cd /app && git pull && npm install && pm2 restart app"
